#!/bin/bash
# sed -i '1,1d' Playlist.m3u  1,1d comando sed que fala para remover da 1 a 1 linha -i fala para modificar
# sed -i y/x/z/ Playlist.m3u  Troca tadas expressões com x para z do arquivo Playlist.m3u. Colocar / sí se for um caracter e nao um comando
# sed -i '/^#d' Playlist.m3u Elimina a expressão # do começo
# sed -i '/^$/d' Playlist.m3u Elimina os espaços em brancos do arquivo porque ela começa e termina sem nenhum caracter
# sed -i 's/^$/Branco/' Playlist.m3u Substitui os espaços em brancos do arquivo porque ela começa e termina sem nenhum caracter
# sed -i 's/fabio/ana/g' Playlist.m3u Substitui todos (comando g) os fabios por ana


function Verifica()
 {
     #Verifica se exit diretorio Musicas
     if [ ! -e $($1) ]; then
         printf "O diretorio %s nao existe" $1 
         mkdir $1
         echo "Agora o diretorio %s foi criado" $1
         echo "Coloque suas musicas aqui"
     fi
    echo $2
     #Verifica se exit PlayList.txt
    if [ ! -z $2 ]; then
         echo "O arquivo nao existe"
         touch $2
         echo "Agora o arquivo foi criado"
     fi
 }

tarefa=$1
case $tarefa in

1)
    echo "Gerador de Playlist"
    Verifica "$Musicas" "PlayList.txt"
    #Cria PlayList.m3u com as musicas em PlayList.txt
    caminho=`echo $PWD/Musicas`
    ls -w 1 ./Musicas/*.mp3 > ./PlayList.txt
    sed -i "s|.\/Musicas|$caminho|g" PlayList.txt 
    cat PlayList.txt > ./PlayList.m3u
    # Toca musica
    mpg123 -v -C -Z --list ./PlayList.m3u
;;

*)
    Verifica "Musicas" "PlayList.txt"
    cat PlayList.txt > ./PlayList.m3u
    # Toca musica
    mpg123 -v -C -Z --list ./PlayList.m3u;;
esac
   
